export const products = [
    {
        name: 'Bivaxduk 3-Pack',
        id: '0',
        price: '199',
        image: require('../images/webshopmixed3.jpg'),
        colors: ['Röd', 'Midnattsblå', 'Blandad'],
        sizes: ['mixed'],
        models:[{
            id: '01',
            color: 'Röd',
            images: [{original: require('../images/red3.jpg'),thumbnail: require('../images/red3.jpg')}, {original: require('../images/redprodukt.jpg'),thumbnail: require('../images/redprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'),thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/redprodukt2.jpg'),thumbnail: require('../images/redprodukt2.jpg')},
                    {original: require('../images/redprodukt3.jpg'),thumbnail: require('../images/redprodukt3.jpg')}],
            size: 'mixed',
            price: '199',
            name: '3-Pack Röd',
            checkoutImage: require('../images/webshopred3.jpg'),
        },
        {
            id: '02',
            color: 'Midnattsblå',
            images: [{original: require('../images/blue3.jpg'),thumbnail: require('../images/blue3.jpg')},{original: require('../images/blueprodukt.jpg'),thumbnail: require('../images/blueprodukt.jpg')}, {original: require('../images/blueprodukt1.jpg'),thumbnail: require('../images/blueprodukt1.jpg')}, {original: require('../images/redblueprodukt.jpg'),thumbnail: require('../images/redblueprodukt.jpg')}],
            size: 'mixed',
            price: '199',
            name: '3-Pack Midnattsblå',
            checkoutImage: require('../images/webshopblue3.jpg'),
        },
        {
            id: '03',
            color: 'Blandad',
            images: [{original: require('../images/mixed3.jpg'),thumbnail:require('../images/mixed3.jpg')}, {original: require('../images/redblueprodukt.jpg'),thumbnail: require('../images/redblueprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'),thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/blueprodukt.jpg'),thumbnail: require('../images/blueprodukt.jpg')},
                    {original: require('../images/redprodukt3.jpg'),thumbnail: require('../images/redprodukt3.jpg')}],
            size: 'mixed',
            price: '199',
            name: '3-Pack Blandad',
            checkoutImage: require('../images/webshopmixed3.jpg'),
        }],
    },
    {
        name: 'Bivaxduk 2-Pack',
        id: '1',
        price: '119',
        image: require('../images/webshopblue2.jpg'),
        colors: ['Röd', 'Midnattsblå', 'Blandad'],
        sizes: ['mixed'],
        models:[{
            id: '11',
            color: 'Röd',
            images: [{original: require('../images/red2.jpg'), thumbnail: require('../images/red2.jpg')}, {original: require('../images/redprodukt.jpg'), thumbnail: require('../images/redprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'), thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/redprodukt2.jpg'), thumbnail: require('../images/redprodukt2.jpg')},
                    {original: require('../images/redprodukt3.jpg'), thumbnail: require('../images/redprodukt3.jpg')}],
            size: 'mixed',
            price: '119',
            name: '2-Pack Röd',
            checkoutImage: require('../images/webshopred2.jpg'),
        },      
        {
            id: '12',
            color: 'Midnattsblå',
            images: [{original: require('../images/blue2.jpg'), thumbnail: require('../images/blue2.jpg')}, {original: require('../images/blueprodukt.jpg'), thumbnail: require('../images/blueprodukt.jpg')}, {original: require('../images/blueprodukt1.jpg'), thumbnail: require('../images/blueprodukt1.jpg')}, {original: require('../images/redblueprodukt.jpg'), thumbnail: require('../images/redblueprodukt.jpg')}],
            size: 'mixed',
            price: '119',
            name: '2-Pack Midnattsblå',
            checkoutImage: require('../images/webshopblue2.jpg'),
        },
        {
            id: '13',
            color: 'Blandad',
            images: [{original: require('../images/mixed2.jpg'), thumbnail: require('../images/mixed2.jpg')}, {original: require('../images/redblueprodukt.jpg'), thumbnail: require('../images/redblueprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'), thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/blueprodukt.jpg'), thumbnail: require('../images/blueprodukt.jpg')},
                    {original: require('../images/redprodukt3.jpg'), thumbnail: require('../images/redprodukt3.jpg')}],
            size: 'mixed',
            price: '119',
            name: '2-Pack Blandad',
            checkoutImage: require('../images/webshopmixed2.jpg'),
        }],
    },
    {
        name: 'Bivaxduk 1-Pack',
        id: '2',
        price: '59',
        image: require('../images/webshopred1.jpg'),
        colors: ['Röd', 'Midnattsblå'],
        sizes: ['20x20', '25x25', '35x35'],
        models:[{
            id: '21',
            color: 'Röd',
            images: [{original: require('../images/red1small.jpg'), thumbnail: require('../images/red1small.jpg')}, {original: require('../images/redprodukt.jpg'), thumbnail: require('../images/redprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'), thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/redprodukt2.jpg'), thumbnail: require('../images/redprodukt2.jpg')},
                    {original: require('../images/redprodukt3.jpg'), thumbnail: require('../images/redprodukt3.jpg')}],
            size: '20x20',
            price: '59',
            name: '1-Pack Röd 20x20',
            checkoutImage: require('../images/webshopred1small.jpg'),
        },
        {
            id: '22',
            color: 'Midnattsblå',
            images: [{original: require('../images/blue1small.jpg'), thumbnail: require('../images/blue1small.jpg')}, {original: require('../images/blueprodukt.jpg'), thumbnail: require('../images/blueprodukt.jpg')}, {original: require('../images/blueprodukt1.jpg'), thumbnail: require('../images/blueprodukt1.jpg')}, {original: require('../images/redblueprodukt.jpg'), thumbnail: require('../images/redblueprodukt.jpg')}],
            size: '20x20',
            price: '59',
            name: '1-Pack Midnattsblå 20x20',
            checkoutImage: require('../images/webshopblue1small.jpg'),
        },
        {
            id: '23',
            color: 'Röd',
            images: [{original: require('../images/red1small.jpg'), thumbnail: require('../images/red1small.jpg')}, {original: require('../images/redprodukt.jpg'), thumbnail: require('../images/redprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'), thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/redprodukt2.jpg'), thumbnail: require('../images/redprodukt2.jpg')},
                    {original: require('../images/redprodukt3.jpg'), thumbnail: require('../images/redprodukt3.jpg')}],
            size: '25x25',
            price: '69',
            name: '1-Pack Röd 25x25',
            checkoutImage: require('../images/webshopred1small.jpg'),
        },
        {
            id: '24',
            color: 'Midnattsblå',
            images: [{original: require('../images/blue1small.jpg'), thumbnail: require('../images/blue1small.jpg')}, {original: require('../images/blueprodukt.jpg'), thumbnail: require('../images/blueprodukt.jpg')}, {original: require('../images/blueprodukt1.jpg'), thumbnail: require('../images/blueprodukt1.jpg')}, {original: require('../images/redblueprodukt.jpg'), thumbnail: require('../images/redblueprodukt.jpg')}],
            size: '25x25',
            price: '69',
            name: '1-Pack Midnattsblå 25x25',
            checkoutImage: require('../images/webshopblue1small.jpg'),
        },
        {
            id: '25',
            color: 'Röd',
            images: [{original: require('../images/red1big.jpg'), thumbnail: require('../images/red1big.jpg')}, {original: require('../images/redprodukt.jpg'), thumbnail: require('../images/redprodukt.jpg')}, {original: require('../images/redprodukt1.jpg'), thumbnail: require('../images/redprodukt1.jpg')}, {original: require('../images/redprodukt2.jpg'), thumbnail: require('../images/redprodukt2.jpg')},
                    {original: require('../images/redprodukt3.jpg'), thumbnail: require('../images/redprodukt3.jpg')}],
            size: '35x35',
            price: '89',
            name: '1-Pack Röd 35x35',
            checkoutImage: require('../images/webshopred1.jpg'),
        },
        {
            id: '26',
            color: 'Midnattsblå',
            images: [{original: require('../images/blue1big.jpg'), thumbnail: require('../images/blue1big.jpg')}, {original: require('../images/blueprodukt.jpg'), thumbnail: require('../images/blueprodukt.jpg')}, {original: require('../images/blueprodukt1.jpg'), thumbnail: require('../images/blueprodukt1.jpg')}, {original: require('../images/redblueprodukt.jpg'), thumbnail: require('../images/redblueprodukt.jpg')}],
            size: '35x35',
            price: '89',
            name: '1-Pack Midnattsblå 35x35',
            checkoutImage: require('../images/webshopblue1.jpg'),
        }],
    },
    {
        name: 'Braständare 3-Pack',
        id: '3',
        price: '30',
        image: require('../images/webshopblue2.jpg'),
        color: 'Röd',
        size: 'mixed',
        checkoutImage: require('../images/webshopred1small.jpg'),
    },
];